nginx:
  image: hellowdocker/nginx
  ports:
    - "8080:80"
  volumes:
    - ./src:/var/www/hellowdocker
    - ./vmconfigs/vhost.conf:/etc/nginx/sites-enabled/default
  links:
    - php

php:
  image: nmcteam/php56
  volumes:
    - ./vmconfigs/php-fpm.conf:/etc/php5/fpm/php-fpm.conf
    - ./src:/var/www/hellowdocker
  links:
    - db

db:
  image: sameersbn/mysql
  volumes:
   - /var/lib/mysql
  environment:
   - DB_NAME=demoDb
   - DB_USER=demoUser
   - DB_PASS=demoPass
